version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./bin/nginx/Dockerfile.dev
    container_name: "${PROJECT_NAME}-NGINX"
    depends_on:
      - api
    restart: "always"
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: ./bin/react18/Dockerfile
    container_name: "${PROJECT_NAME}-REACT"
    restart: "on-failure"
    volumes:
      - ./capslol_frontend/src:/app/src

  api:
    build:
      context: .
      dockerfile: ./bin/${NODEJS17}/Dockerfile.dev
    container_name: "${PROJECT_NAME}-${NODEJS17}"
    restart: "on-failure"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - database
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - CORS_ORIGINAL=${CORS_ORIGINAL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - FE_APP_URL=${FE_APP_URL}
    volumes:
      - ./capslol_backend/src:/app/src
  database:
    build:
      context: .
      dockerfile: "./bin/${POSTGRES12}/Dockerfile"
    container_name: "${PROJECT_NAME}-${POSTGRES12}"
    restart: "always"
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  admin:
    build:
      context: .
      dockerfile: "./bin/${PHP_ADMIN}/Dockerfile"
    container_name: "${PROJECT_NAME}-${PHP_ADMIN}"
    restart: "always"
    depends_on:
      - database
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - "5050:5050"
