version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./bin/nginx/Dockerfile
      args:
        - clientId=${GOOGLE_CLIENT_ID}
        - productionURL=${REACT_APP_SERVER_URL}
        - socketURL=${REACT_APP_SOCKET_URL}

    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./logs/:/var/log/nginx/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./bin/nginx/default.conf:/etc/nginx/default.conf

  migration:
    build:
      context: .
      dockerfile: ./bin/${NODEJS17}/Dockerfile.migration
    container_name: "migration"
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - database

  seeding:
    build:
      context: .
      dockerfile: ./bin/${NODEJS17}/Dockerfile.seeding
    container_name: "seeder"
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - database
      - migration

  api:
    build:
      context: .
      dockerfile: ./bin/${NODEJS17}/Dockerfile
    container_name: "${NODEJS17}"
    restart: "on-failure"
    depends_on:
      - database
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - CORS_ORIGINAL=${CORS_ORIGINAL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - FE_APP_URL=${FE_APP_URL}

  database:
    build:
      context: .
      dockerfile: "./bin/${MYSQL8}/Dockerfile"
    container_name: "${MYSQL8}"
    restart: "always"
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  admin:
    build:
      context: .
      dockerfile: "./bin/${PHP_ADMIN}/Dockerfile"
    container_name: "${PHP_ADMIN}"
    restart: "always"
    depends_on:
      - database
    environment:
      - PMA_HOST=${PMA_HOST}
    ports:
      - "5050:80"
