version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./bin/nginx/Dockerfile
      args:
        - clientId=${GOOGLE_CLIENT_ID}
        - productionURL=${REACT_APP_PROD_SERVER_URL}
    restart: "always"
    ports:
      - "8080:8080"
    volumes:
      - ./logs/:/var/log/nginx/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./bin/nginx/default.conf:/etc/nginx/default.conf

  api:
    build:
      context: .
      dockerfile: ./bin/${NODEJS17}/Dockerfile
      args:
        - host=${DATABASE_HOST}
        - port=${DATABASE_PORT}
        - databaseName=${DATABASE_NAME}
        - username=${DATABASE_USERNAME}
        - password=${DATABASE_PASSWORD}
    container_name: "${PROJECT_NAME}-${NODEJS17}"
    restart: "on-failure"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - database
      - nginx
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - CORS_ORIGINAL=${CORS_ORIGINAL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - FE_APP_URL=${FE_APP_URL}

  database:
    build:
      context: .
      dockerfile: "./bin/${MYSQL8}/Dockerfile"
    container_name: "${PROJECT_NAME}-${MYSQL8}"
    restart: "always"
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  # admin:
  #   build:
  #     context: .
  #     dockerfile: "./bin/${PHP_ADMIN}/Dockerfile"
  #   container_name: "${PROJECT_NAME}-${PHP_ADMIN}"
  #   restart: "always"
  #   depends_on:
  #     - database
  #   environment:
  #     - PMA_HOST=${PMA_HOST}
  #     - PMA_USER=${PMA_USER}
  #     - PMA_PASSWORD=${PMA_PASSWORD}
  #   ports:
  #     - "5050:5050"
